# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'CheckoutExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CheckoutExample
end

target 'CheckoutSDK-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CheckoutSDK-iOS
pod 'TapUIKit-iOS'
pod 'TapNetworkKit-iOS'
pod 'TapApplicationV2'
end
